### ISSUE TITLE
How to deal with a partial PR?

### ISSUE THREAD

**Issue by sintaxi** [bcgov/BC-Policy-Framework-For-GitHub#27]
In my experience dealing with PRs on my open source projects is that the majority of PRs will be partially implemented/working. I'd be curious how this could be dealt with in respect to the bounty. Ideally, we find a way for people to work together on solutions rather than duplicating efforts. Thoughts?

**Comment by howardroark** [comment]
Yeah it seems like the $1000 bounty concept depends on completeness. Ostensibly, completeness is sort of an ideal that may not be truly achievable.  What would nice if the $1000 can could be "allocated" somehow and paid out as completeness is worked towards.

Perhaps you could have a top level pool of funds that has a two way relationship with pull requests as they grow and shrink in potential... vs tying up funds in endless semantic debates.

**Comment by kelpisland** [comment]
This is a great discussion! I want say that the intention of the $1000 pay for pull is to build community and reward people for their effort. I like the notion of a "working towards completeness" model to encourage collaboration, what do you think would a reasonable way to allocate/split a bounty between collaborators?

I'd like to move this issue to our bcdevexchange/rapid-adoption repo so it is linked to place where we are building the pay for pull wiki. Any objections?

**Comment by kelpisland** [comment]
This issue was moved to BCDevExchange/rapid-adoption#1
