### ISSUE TITLE
Broken Github links 

### ISSUE THREAD

**Issue by gcperk** [bcgov/BC-Policy-Framework-For-GitHub#41]
Hi, I noticed a number of you "how-to" steps for Github are giving a 404 error. 
These include: 
1) https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Gov-Org-HowTo/Creating-And-Deleting-Repos.md
2) https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Gov-Org-HowTo/using-licenses.md

Thanks, Gen

**Comment by patricksimonian** [comment]
PR #40 addresses issue 1, 

Issue #43 has been created to address the second issue! Thanks!
