### ISSUE TITLE
Devhub Issue: Github Practices in Gov [Using Licenses Link Broken]

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/BC-Policy-Framework-For-GitHub#43]
> path: (do not delete) https://github.com/bcgov/BC-Policy-Framework-For-GitHub/blob/master/BC-Open-Source-Development-Employee-Guide/appropriate-use.md
 > (do not delete) devhub page: http://0.0.0.0:8000/Code-Management/Github-Practices-in-Gov/

## Devhub Content Issue

The link to Using Licences is Broken, this file does not exist anymore!

**Comment by patricksimonian** [comment]
this link would be a good drop in replacement https://help.github.com/en/articles/licensing-a-repository

**Comment by MonkmanMH** [comment]
Can we get an update on this issue, please? Licensing is an important matter, and clarity on our options is vital!

**Comment by patricksimonian** [comment]
the link has been fixed as referenced on June 25 :) Feel free to checkout  https://developer.gov.bc.ca/Code-Management/Licensing-Your-Project

the link  I had posted above is a more exhaustive list of  licences. I'd recommend checking the former link first
